model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"

sandbox_mode = "danger-full-access"
file_opener = "vscode"

[sandbox_workspace_write]
network_access = true

[features]
web_search_request = true
parallel = true
apply_patch_freeform = true
shell_snapshot = true
unified_exec = true
rmcp_client = true
steer = true
collab = true

[tui]
notifications = true

[mcp_servers.sentry]
command = "bunx"
args = ["-y", "mcp-remote@latest", "https://mcp.sentry.dev/mcp"]

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=wesvzzzxicieygbvrlwh&read_only=true"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
startup_timeout_ms = 20_000

[mcp_servers.sketch]
url = "http://localhost:31126/mcp"